### ISSUE TITLE
missing variants in pre-computed vcf

### ISSUE THREAD

**Issue by adelpozomt** [broadinstitute/SpliceAI-lookup#10]
Hello everyone,

I participate in a local bioinfo group that is performing some splicing tools benchmarking and we have came across a particular case of a variant (chrX:49689926T>G) in a canonical splicing donor that is missing in the pre-computed vcf. However, SpliceAI-lookup returns a prediction with the 'pre-computed' option on. 

We would like to know if the web client calculates the score when the variant is missing even with it is wanted to use the pre-computed scores. Otherwise, what is the referece pre-computed data used by SpliceAI-lookup?

Thanks in advance!

**Comment by bw2** [comment]
Hi @adelpozomt , yes, as you suggested - spliceailookup runs the model to calculate the score if the variant is missing from the pre-computed tables. I just added some help text to the "Use precomputed scores" ? icon to clarify this.
