### ISSUE TITLE
ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server is down or your internet isn't working.

### ISSUE THREAD

**Issue by athomas22** [broadinstitute/SpliceAI-lookup#13]
Hi, I am getting this error when trying to query:
ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server is down or your internet isn't working.
Please advise.  Thank you

**Comment by bw2** [comment]
Hi @athomas22 , thanks for reporting this error. There may have been intermittent problems earlier today, but everything appears to be working currently. Let me know if you're continuing to see errors.

**Comment by athomas22** [comment]
I am still seeing the same error.  It seems to be a persistent problem, as I noted the same yesterday.  I have tried using pre-computed scores as well to no avail.  Thank you for taking a look at this.

**Comment by bw2** [comment]
If you continue to see errors, please reopen this issue.
