### ISSUE TITLE
certfile does not exist

### ISSUE THREAD

**Issue by pablo-baeza** [broadinstitute/SpliceAI-lookup#14]
Hello,

I am trying to run the API following the instructions on the readme file. When I run `start_server.sh` it returns the following error:

`ValueError: certfile "../spliceailookup-api_broadinstitute_org.cert" does not exist`

I would appreciate it if you could help me figure out what it is I'm doing wrong. Thanks a lot!

**Comment by bw2** [comment]
Hi @pablo-baeza , I've added a `./start_local_server.sh ` script that shouldn't have this error. Please try that, and let me know if you run into further issues.
