### ISSUE TITLE
Different score between local implmentation of spliceai and spliceai-lookup

### ISSUE THREAD

**Issue by wigge206** [broadinstitute/SpliceAI-lookup#15]
Hi, 
I have run the spliceai locally (v1.3.1) on > 30,000 variants and decide to sanity check much results against those in you lookup table. For the majority the scores seem to match. However, there are some variants that seem to be discordant between our two datasets. 

These seem to be the case for variants within particular genes/transcripts. For example:

ID| Local | | | | Lookup-table | | | | |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | 
 -- | Symbol | AG | AL | DG | DL | AG | AL | DG | DL
chr1_16069287_C_T | TMEM82 | 0.00 | 0.04 | 0.00 | 0.02 | 0 | 0.03 | 0 | 0.01
chr1_16069297_C_T | TMEM82 | 0.04 | 0.01 | 0.04 | 0.00 | 0.03 | 0.02 | 0.03 | 0

Spliceai was run with max distance and raw score type on hg19
Are you able to replicate the error? Any thoughts to why variants in some genes are differing?

**Comment by bw2** [comment]
We might be using different transcript models. 
SpliceAI-lookup is currently using gencode.v38lift37.annotation.txt.gz for build 38, processed using 
https://github.com/broadinstitute/SpliceAI-lookup/blob/master/annotations/convert_gencode_gtf_to_spliceai_annotation_input_file.py
