### ISSUE TITLE
SpliceAI Site Down?

### ISSUE THREAD

**Issue by redmoon6584** [broadinstitute/SpliceAI-lookup#16]
To Whom It May Concern,

I've been getting the following error since yesterday afternoon, although it seemed to resolve yesterday but is back again today.

"ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server is down or your internet isn't working."

Is there an issue with the site?

Thanks!

**Comment by bw2** [comment]
Apologies, the server did go down this morning, but is back up now.
