### ISSUE TITLE
fix parseVariantToHGVS for multinucleotide variants

### ISSUE THREAD

**Issue by leekaiinthesky** [broadinstitute/SpliceAI-lookup#18]
Hi @bw2,

When I try to put a variant like 11:94464112CC>TG into the lookup, I get an "unexpected reference allele" Ensembl API error, which I think can be fixed by changing the parseVariantToHGVS logic to the following (please double check):

```
          if (ref.length > 1 && alt.length > 1) {
            variant = chrom + ":g." + pos + "_" + (pos + ref.length - 1) + "delins" + alt
          } else if ref.length > 1 {
            //deletion (https://varnomen.hgvs.org/recommendations/DNA/variant/deletion/)
            variant = chrom + ":g." + (pos + 1) + "_" + (pos + ref.length - 1) + "del"
          } else if alt.length > 1 {
            //insertion (https://varnomen.hgvs.org/recommendations/DNA/variant/insertion/)
            variant = chrom + ":g." + pos + "_" + (pos + 1) + "ins" + alt.slice(1)
          } else {
            variant = chrom + ":g." + pos + ref + ">" + alt
          }
```

This is somewhat related to #1, but I created a separate issue, since that one was about whether SpliceAI can handle these variants whereas this issue is about the front end. Nevertheless I believe both issues can be resolved, since SpliceAI is able to handle multinucleotide variants now. In the meantime – thank you for this extremely useful tool!

Lee-kai

**Comment by bw2** [comment]
Hi Lee-kai, thank you for the suggested fix. 
Let me know if I missed it, but I don't think SpliceAI has added support for "delins" variants yet (https://github.com/Illumina/SpliceAI/commits/master).

**Comment by leekaiinthesky** [comment]
Hm, I must have been thinking of something else – sorry about that. I agree with you that it has not been added yet... Oh well. Thanks anyway for your attention.
