### ISSUE TITLE
SpliceAi lookup issue

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/SpliceAI-lookup#2]
Hello,

I get an error looking up 3-38663893-G-A (hg37). The variant I am trying to look up is https://gnomad.broadinstitute.org/variant/3-38663893-G-A?dataset=gnomad_r2_1

Thanks for taking a look.

**Comment by bw2** [comment]
Hi Lynn, sorry I missed this earlier. It should be working now. 
Please try again. If you continue to see an error, please share the error message.
