### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by redmoon6584** [broadinstitute/SpliceAI-lookup#20]
I was trying to run SpliceAI for a single variant and keep getting the following error message: 
"ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server is down or your internet isn't working."

I thought I would report it in case it is a server issue and unknown to the team.

Screenshot: 
![image](https://user-images.githubusercontent.com/43679337/172168224-32f96372-f94a-468d-bab2-f4c28b84b641.png)

Thank you for your assistance!

**Comment by bw2** [comment]
Apologies, this has been fixed.
