### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by redmoon6584** [broadinstitute/SpliceAI-lookup#23]
Hello,

I believe the SpliceAI server(s) may have been down since last night at ~12:00am Eastern.  I tried to run a few different variants and got the same error message for all of them, which still persists: "ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server is down or your internet isn't working."

URL (copy-paste the url of a page where you see the issue or have a feature suggestion):
https://spliceailookup.broadinstitute.org/#variant=22%3A30035210-G-A&hg=37&distance=10000&mask=0&precomputed=0
https://spliceailookup.broadinstitute.org/#variant=2%3A215674131-T-C&hg=37&distance=10000&mask=0&precomputed=0
https://spliceailookup.broadinstitute.org/#variant=5%3A1282529-G-A&hg=37&distance=10000&mask=0&precomputed=0
https://spliceailookup.broadinstitute.org/#variant=14%3A68292236-G-A&hg=37&distance=10000&mask=0&precomputed=0
https://spliceailookup.broadinstitute.org/#variant=4%3A57797879-A-G&hg=37&distance=10000&mask=0&precomputed=0

Screenshot (optionally, paste or drag-drop an image here):
![image](https://user-images.githubusercontent.com/43679337/175545228-cb2f0ffb-6814-4b91-8186-af7433b80e67.png)

Any help would be much appreciated so I can finish up curation of the aforementioned variants.  Thank you!

**Comment by bw2** [comment]
Apologies for missing this earlier. All should be working now.
