### ISSUE TITLE
hg19 server seems to be down

### ISSUE THREAD

**Issue by elodiep-3483** [broadinstitute/SpliceAI-lookup#24]
URL (copy-paste the url of a page where you see the issue or have a feature suggestion):
https://spliceailookup.broadinstitute.org/#variant=NM_001128849.3(SMARCA4)%3Ac.4266%2B5G%3ET&hg=37&distance=1000&mask=0&precomputed=0

Screenshot (optionally, paste or drag-drop an image here):
<img width="1432" alt="Screen Shot 2022-07-20 at 4 57 18 PM" src="https://user-images.githubusercontent.com/109698418/180080799-54b069df-b521-4430-983c-0265448741c9.png">

**Comment by bw2** [comment]
Apologies. I've rebooted the server and added more resources. Please post again if the problem returns.
