### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by poppies700** [broadinstitute/SpliceAI-lookup#25]
URL (copy-paste the url of a page where you see the issue or have a feature suggestion):

ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server is down or your internet isn't working.

**Comment by redmoon6584** [comment]
I agree.  I think this is may be a SpliceAI server issue since it's been persistent since yesterday and not only me.

**Comment by bw2** [comment]
Apologies. I've rebooted the server and added more resources. Please post again if the problem returns.
