### ISSUE TITLE
Duplicated data in spliceAI vcf

### ISSUE THREAD

**Issue by forrestzhaosen** [broadinstitute/SpliceAI-lookup#27]
Hi,

I downloaded the spliceAI vcf for all snv and indel to annotated genome sequencing data.
I noted that there are multiple lines of spliceAI annotation for a single variant in a single gene and assume that these conrrespond to different transcripts, but there is no transcript information in the spliceAI vcf.
So I was wondering whether you have any suggestions on that.

Best,
Sen Zhao

**Comment by bw2** [comment]
Hi, we're not the authors of SpliceAI (the prediction model) or the SpliceAI VCF. We just built the spliceai-lookup web server. 
It's better to open this issue the SpliceAI repo @ https://github.com/Illumina/SpliceAI/issues
You may find closed issues there that already address this question.
