### ISSUE TITLE
TET2 Cannonical transcript not selected

### ISSUE THREAD

**Issue by cpsosa0006** [broadinstitute/SpliceAI-lookup#28]
[https://spliceailookup.broadinstitute.org/#variant=chr4-106162586-G-T&hg=37&distance=50&mask=0&precomputed=0URL (copy-paste the url of a page where you see the issue or have a feature suggestion):](https://spliceailookup.broadinstitute.org/#variant=chr4-106162586-G-T&hg=37&distance=50&mask=0&precomputed=0)

The score is computed selecting Use Illumina's pre-computed scores: yes, result is:

Screenshot (optionally, paste or drag-drop an image here):
![image](https://user-images.githubusercontent.com/70243274/214720118-2588ff42-4490-4024-9b20-c0953fa60524.png)

However, when selecting 

The score is computed selecting Use Illumina's pre-computed scores: no, result is:

![image](https://user-images.githubusercontent.com/70243274/214720508-c66f11c5-f46e-40d2-bad1-4ad0ce227d59.png)

and the highest score is the canonical transcript with the highest score but it is not consistent when using yes.  Why is the difference?

Thanks,

**Comment by cpsosa0006** [comment]
Is this team still supporting spliceAI?

**Comment by bw2** [comment]
Hi @cpsosa0006 , the Illumina pre-computed scores are based on gencode v26, while the other scores are based on gencode v42 - so that's the likely reason.

**Comment by bw2** [comment]
I'm not part of the SpliceAI team. I just made this web server to look up or compute SpliceAI scores developed @ Illumina.
