### ISSUE TITLE
different score for same variant

### ISSUE THREAD

**Issue by vasvale** [broadinstitute/SpliceAI-lookup#29]
hg38 |   | NC_000011.10:g.47343144_47343146dup
hg19 |   | NC_000011.9:g.47364696_47364697insACC
should be the same variant but have different scores?

Thanks

Vale

**Comment by vasvale** [comment]
it seems that you get a different score whether you input the variant as insertion or as a duplication

hg19

NC_000011.9:g.47364695_47364697dup
--
NC_000011.9:g.47364694_47364695insACC


same variant , different score

**Comment by vasvale** [comment]
NC_000011.9:g.47364695_47364697dup is interpreted as 11-47364697-C-CACC but it should be 

11-47364694 - T-TACC ?

if this is ambiguous which is the correct score? or it stay ambiguous?

**Comment by vasvale** [comment]
actually, considering that the resulting sequence is identical shouldn't the score be the same?

TAC|ct  becomes TACCAC|ct  for both  11-47364697-C-CACC or 11-47364694 - T-TACC

**Comment by bw2** [comment]
I'm not sure. Unless SpliceAI-lookup is reporting scores incorrectly (ie. is showing something different from what SpliceAI is computing for these variants), this question is more relevant for the SpliceAI repo @ https://github.com/illumina/SpliceAI
