### ISSUE TITLE
Unable to compute scores for multiple variants

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/SpliceAI-lookup#3]
Hello,

I have received this error message for multiple variants, no matter which format I try - ERROR: Unable to compute scores for X-77447857-G-A. Please check that the genome version and reference allele are correct, and the variant is either exonic or intronic in Gencode v24.

Example: X:77447857:G:A

<img width="1255" alt="Screen Shot 2021-01-21 at 10 38 31 AM" src="https://user-images.githubusercontent.com/37872186/105373588-d6cebf00-5bd4-11eb-833e-35dc8e9829ed.png">

**Comment by bw2** [comment]
Hi Lynn,  
Thanks for reporting this issue. This variant is in the FGF16 gene which is present in Gencode v24, but for unclear reasons wasn't included in the annotations used by the SpliceAI model. The list of all currently-included genes is:
https://raw.githubusercontent.com/Illumina/SpliceAI/master/spliceai/annotations/grch38.txt
I will see if I can update these annotations go the full set of Gencode v36 genes.

**Comment by bw2** [comment]
This has been fixed
https://spliceailookup.broadinstitute.org/#variant=X-77447857-G-A

![image](https://user-images.githubusercontent.com/6240170/106838135-b5a4ae80-6669-11eb-9f23-5bd90576e90e.png)

**Comment by lynnpais** [comment]
Hi Ben,

Thanks so much for doing this! Hopefully it wasn't too much additional
work.

Much appreciated.

Lynn
