### ISSUE TITLE
Feature Request - Predictions for cryptic sites with no difference in score between ref and alt alleles

### ISSUE THREAD

**Issue by NM-G08** [broadinstitute/SpliceAI-lookup#30]
Hello,

I was wondering if it would be possible to alter the SpliceAI website to show users splicing predictions for cryptic splice sites regardless of whether or not there is a score change at that position.  I emailed Dr. Kishore Jaganathan, and he indicated that 
this data is of course part of the algorithm (just not a typical output), and can be found either by using the code in [FAQ no 3](https://github.com/Illumina/SpliceAI/blob/master/README.md) or line [https://github.com/Illumina/SpliceAI/blob/b083eb5f8f0d773c7c977aac0c45880d47ca18b7/spliceai/utils.py#L178](https://github.com/Illumina/SpliceAI/blob/b083eb5f8f0d773c7c977aac0c45880d47ca18b7/spliceai/utils.py#L178), the latter of which should represent raw scores for the splice sites present in the reference sequence.

The reason I'm asking about this is because I noticed this as a limitation for SpliceAI in comparison to MaxEntScan or Splice SIte Finder-like, which may prevent ClinGen groups from recommending a single splicing algorithm alone in determining application of PVS1 and/or PP3/BP4.

As an example, SpliceAI predicts the loss of canonical acceptor splice site and the gain of a cryptic acceptor splice site at c.74 for NM_004168.2(SDHA):c.64-2A>G. However, MaxEntScan additionally predicts the existence of cryptic acceptor sites at c.64-54 and c.64-39, and RNA data shows that while there is a small proportion of RNA that is derived from c.74 (predicted by both SpliceAI and MES), the majority of transcripts utilize the c.64-54 site (only predicted by MES).

Thank you in advance for your help with this inquiry!
NM, ClinGen VCEP

**Comment by bw2** [comment]
Hi, this is something I've also been thinking about. Is there a user interface that you already like for how to show these absolute scores?

**Comment by redmoon6584** [comment]
Hi,

I'm used to the interface and reports in Alamut Visual Plus.  The interface may be more difficult, but the reports are fine too (all the information is in there) and seems to be more similar to the current interface.

*Default display of algorithms' predictions (can move right/left along the sequence or zoom in/out):
![image](https://user-images.githubusercontent.com/43679337/218168346-f364d4e1-c123-401d-8fd9-03e1948033df.png)

*Same display, but with differences between the reference (top tracks) and mutated allele (bottom tracks) highlighted:
![image](https://user-images.githubusercontent.com/43679337/218168576-fc1083fb-47df-4144-99d8-188320810192.png)

*[Alamut Visual Plus v1.7 Splicing Report.pdf](https://github.com/broadinstitute/SpliceAI-lookup/files/10710162/Alamut.Visual.Plus.v1.7.Splicing.Report.pdf)

Please let me know if there are further questions!  Thanks!

*The above images and files are from Alamut Visual Plus version v1.7 | © 2022 SOPHiA GENETICS.

**Comment by redmoon6584** [comment]
Hello,

There was an ACMG presentation regarding the upcoming iteration of the variant curation guidelines.  I wanted to share that their draft (available [here](tinyurl.com/ACMG23)) includes use of SpliceAI for assessing splicing effects.  Given this specification, I think it is even more important to add this feature so cryptic sites that exist for both the reference and alternate alleles can be known to users.

Thanks again,
NM

**Comment by bw2** [comment]
I've been thinking about this. 
Initially I was going to use IGV.js for visualizing scores like this, but I'm now thinking that won't work because IGV.js shows only reference bases/positions, but here you need to potentially add inserted sequence and show scores for bases that are not in the reference, so I need to think about how to do that, but would appreciate any suggestions.

**Comment by bw2** [comment]
After thinking about this more, an IGV.js visualization might be good enough. I will share a proposed design once I have it.

**Comment by NM-G08** [comment]
Hello bw2,

I think seeing the reference and alternate allele scores is a good addition.  However, I think:
1. If there is creation of a cryptic site within an insertion sequence (like your example), yes, we would want to know if somehow there is a significant prediction there.
2. If the reference sequence has a natural cryptic site that is not typically used in splicing, but loss of a canonical splice site could potentially then allow for its use, we would want to see that.  I do not think the IGV.js visualization is good enough for this, because it would require additional rows and pre-mRNA positions for donor and acceptor sites, but they technically wouldn't fall under the donor/acceptor "gain" or "loss" headers, since the probabilities should be identical between the ref score and alt score columns.

Hope that makes sense, but do let me know if there are questions.

Thanks,
NM

**Comment by NM-G08** [comment]
Here's a rough example of what I think SpliceAI could look like for the SDHA example above.
![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/7c8442ea-bdb2-4033-8b18-6b7eb5701b10)

**Comment by bw2** [comment]
There's a dev. version with upcoming features and visualizations @

https://broadinstitute.github.io/SpliceAI-lookup-dev/index.html#variant=2%3A178581491%20ATACT%3EA&hg=38&distance=500&mask=1

If you have time to take a look, I would appreciate your feedback based on our discussion above. 
The visualization is quite different from Alamut, but is meant to concisely show the full range of info contained in SpliceAI (and Pangolin) predictions. There are also many reference tracks which will be made optional / selectable later.

**Comment by NM-G08** [comment]
@bw2 I'm sorry I missed your update last month.  I have since noticed that the development site you shared went into production.  I took a look at the new site in the context of the SDHA example I initially sent.  I see that the IGV visualization does capture the possibility of its existence (SpliceAI:raw indicates that it exists based on the score being >0.01).  What I don't quite understand after looking at that track is why the prediction at c.64-39 (circled in yellow in the image below), doesn't show up in the table.  In our initial discussions, it seemed like the delta score at this position was going to be 0, which is why it doesn't populate the table.  But it actually looks like the delta score is 0.5 at this position and even 0.49 for c.64-54, so I would have thought it would make the table view.  Furthermore, the website is showing the c.64-39 prediction as green in spite of the delta score being greater than/equal to 0.5.  Do you know what is happening here?

![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/0454dcca-f54c-446b-8a69-f3b77531b138)

I also checked this out in the context of the duplication issue (https://github.com/broadinstitute/SpliceAI-lookup/issues/31) - essentially to see if visualization helped resolve the discrepancy with the positions - but visualization doesn't seem to be an option for duplications and presumably deletions since the actual variant event cannot be displayed.  That is ok, because I think just knowing that we have to use the HGVS nomenclature as the input provides a solution.

**Comment by bw2** [comment]
Hi @NM-G08 , 
It looks like the bug with the color being green @ 0.5 is due to a rounding error when javascript computes 0.58 minus 0.08:

<img width="175" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/05782a9b-8c4c-4935-8c89-e561a9454520">

I've now added some logic to handle this, so it now looks like:

<img width="1289" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/ad3abca1-c2b4-46b6-ae1b-8363d4c620d9">

As far as the 0.5 score not showing up in the table, this is by design, and mimics the official Illumina SpliceAI model which only returns 4 scores for a given variant: acceptor gain, acceptor loss, donor gain, donor loss. Each of the 4 scores is the maximum score in that category within the user-specified window around the variant. In your example, the maximum acceptor gain is 0.89 @ position chr5:223,492 , so that's what's shown in the table.

**Comment by NM-G08** [comment]
Thank you so much for the quick fix!  Also thanks for the explanation regarding the maximum of 4 scores being returned.  I had thought in the past I had seen some lines that had multiple positions, but perhaps I was recalling incorrectly or things have changed.  Either way, this visualization does fix this issue - so much appreciated!  The new features in general are beautiful!
