### ISSUE TITLE
Max distance = 50  does't show the transcripts ID info

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [broadinstitute/SpliceAI-lookup#35]
Hi SpliceAI-lookup team, 

We have noticed that when the Max distance is  500 the output looks OK as shown below 

![500](https://github.com/broadinstitute/SpliceAI-lookup/assets/74112779/7e8686cc-a002-4bae-b5d4-8b98831fd0a9)

However, if we change that parameter to 50, we are not able to see some info such as the transcript IDs as shown below

![50](https://github.com/broadinstitute/SpliceAI-lookup/assets/74112779/858ef703-2413-4a90-af84-694ff8d5e575)

Is this due to an bug? or because when the Max distance is low, those data is not given. I have been playing,  changing the Max distance and until 51 seems to be ok

![51](https://github.com/broadinstitute/SpliceAI-lookup/assets/74112779/48974c1f-31ef-4cfd-99c5-c9a24aae5dc8)

Thanks

Manuel

**Comment by bw2** [comment]
Thanks, yes, this was a bug and is now fixed.

**Comment by bw2** [comment]
The bug was that - when you set the max distance to 50bp, the server went back to using Illumina precomputed scores.
