### ISSUE TITLE
Linkouts under Pangolin results do not work

### ISSUE THREAD

**Issue by gm-bee** [broadinstitute/SpliceAI-lookup#48]
Hi,
Under all results there are linkouts to various other services (OMIM, etc). The links under the SpliceAI results work, but the ones under the Pangolin results are broken. 

https://spliceailookup.broadinstitute.org/#variant=NM_001165963.4(SCN1A)%3Ac.383C%3ET&hg=37&distance=500&mask=1

Thanks!

**Comment by gm-bee** [comment]
It would also be helpful if these results called out the gene that matched the Ensembl transcript - like it does for the SpliceAI results - please.

**Comment by bw2** [comment]
This has been fixed.
