### ISSUE TITLE
SpliceAI will not output results.

### ISSUE THREAD

**Issue by redmoon6584** [broadinstitute/SpliceAI-lookup#5]
To Whom It May Concern,

I am trying to run SpliceAI for a BRCA1 variant in hg19 (chr17-41246372-C-T) with 10000 max distance, but I keep getting the following error message regardless of whether I do or do not use the pre-computed scores:
"ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server or your internet isn't working."

My internet is working, so I wanted to alert you that perhaps there is an API server issue that you are not yet aware of.

Thank you!

**Comment by bw2** [comment]
Thanks for letting me know.  Someone was running a script that was making 10+ requests per minute, so I've 
now added per-user request rate limits which should make the API more resilient going forward. 
The server is now back online.
