### ISSUE TITLE
Annotation not loading

### ISSUE THREAD

**Issue by cmkoellner** [broadinstitute/SpliceAI-lookup#50]
Please paste the url of the results page and the variant search string as text here (unless this isn't about a specific variant).
https://spliceailookup.broadinstitute.org/#variant=NM_005228.3(EGFR)%3Ac.786C%3ET%20(p.Asp262%3D)&hg=37&distance=500&mask=0

When clicking submit, the table looks like it might load (spinning wheel), but then goes to a blank section.

---
If you'd like to also share a screenshot:
MacOS:   Press Command+Shift+4, select a region of the page, then paste the image here.
Windows:  Press Windows Logo Key + PrtScn   or   Fn + Windows logo key + Space Bar. Then, in File Explorer, open the Pictures > Screenshots folder and drag the im
![Snap5](https://github.com/broadinstitute/SpliceAI-lookup/assets/142812254/04ad2147-2a13-422b-9246-4dd6c6c57c5d)
age here.

**Comment by bw2** [comment]
Hi, I'm not able to recreate this issue. If you are continuing to see this, can you share your operating system version and browser type/version?
