### ISSUE TITLE
How can I modify the Gene annotation file in your repository.

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [broadinstitute/SpliceAI-lookup#53]
Spliceai in its repository (https://github.com/Illumina/SpliceAI) allows to modify the Gene annotation file with the -D option. How can I do this in your server.py script??

Ideally, what I looking for is a similar approach to leave my custom gene annotation file outside the container (e.g. in the separated directory I have for all ref_files) and be able to modify this file when needed. It should be great if this -D option is somehow added in your server.py script.

**Comment by Manuel-DominguezCBG** [comment]
Sorry, I have just seen your annotation folder. Forget this

**Comment by bw2** [comment]
One issue is that there are multiple annotation files so that server.py can support both hg19 and hg38, etc.
Their paths are defined here:
https://github.com/broadinstitute/SpliceAI-lookup/blob/master/server.py#L76-L82

Which of these are you looking to customize? 
Would it be sufficient for me to make these filenames more generic so you can just copy your version(s) of these files into those locations (for example, I can call them `./annotations/annotation.transcript_annotations.json` instead of `./annotations/gencode.{GENCODE_VERSION}lift37.basic.annotation.transcript_annotations.json`)?

**Comment by Manuel-DominguezCBG** [comment]
Let me discuss this with my team just to make sure how important is this for them. I will come back to you?

**Comment by Manuel-DominguezCBG** [comment]
In the meantime, I have checked the annotation files you mentioned in your comments. I think they are not the one I mean. The one I may need to modify is this https://raw.githubusercontent.com/Illumina/SpliceAI/master/spliceai/annotations/grch37.txt

I put all your annotation files outside the container in case I need to modify them in the future. But these two txt files are not in your annotation set that is these annotations % ls
```
ENST_to_RefSeq_map.txt
convert_gencode_gtf_to_spliceai_annotation_input_file.py
download_ENSG_to_RefSeq_mapping.sh
gencode.v43.annotation.db
gencode.v43.annotation.gtf.gz
gencode.v43.annotation.txt.gz
gencode.v43lift37.annotation.db
gencode.v43lift37.annotation.gtf.gz
gencode.v43lift37.annotation.txt.gz
gencode.v43lift37.annotation.without_chr_prefix.db
gencode.v43lift37.annotation.without_chr_prefix.gtf.gz
update_annotation_txt_files.sh
update_pangolin_db_files.sh
upload_annotations_to_server.sh
```
and the two fasta files. I have all of them outside the container but the  `spliceai/annotations/grch37.txt` is in the container. Is this correct?

**Comment by bw2** [comment]
It's good practice to keep all data & annotations files outside the container (especially the larger files). 
My `gencode.v43lift37.annotation.txt.gz` and `gencode.v43.annotation.txt.gz` are the same format as the 2 files you listed.
I have been generating these files for the latest gencode annotations using the steps described @ https://github.com/broadinstitute/SpliceAI-lookup/blob/master/annotations/README.md


https://github.com/bw2/SpliceAI
I have modified SpliceAI a lot over the past year in my fork @

**Comment by Manuel-DominguezCBG** [comment]
I close this as I know now how to modify this. Thanks!!!
