### ISSUE TITLE
Table layout

### ISSUE THREAD

**Issue by cmschwanke** [broadinstitute/SpliceAI-lookup#55]
Purely aesthetic, perhaps, but I would prefer the delta score be the last column of the table on the right.  It gets lost in the center of the table as it is, and I've had lab staff mistakenly list the ALT score as the delta because it's not intuitive.

Thank you for the resource! It's very helpful.

REQUIRED: If the issue is about a specific variant or results page (or you have an example), please copy-paste the variant here and/or provide a link to the results page where you see the issue. 

---
OPTIONAL: If you'd like to also share a screenshot:

MacOS:   Press Command+Shift+4, select a region of the page, then paste the image here.
Windows:  Press Windows Logo Key + PrtScn   or   Fn + Windows logo key + Space Bar. Then, in File Explorer, open the Pictures > Screenshots folder and drag the image here.

**Comment by bw2** [comment]
Thanks for the feedback. 
We removed color from the REF/ALT columns in the BETA version where we're testing out future features - for example
https://broadinstitute.github.io/SpliceAI-lookup-dev/index.html#variant=chr8-140300616-T-G&hg=38&distance=500&mask=1
but we can also try different column order. 
Another option is to hide REF/ALT columns by default and provide a button to show them. 
If you have a preference, let us know.

**Comment by bw2** [comment]
The REF & ALT columns are now hidden by default on the BETA version of the site @ https://broadinstitute.github.io/SpliceAI-lookup-dev/index.html
and the main version of the site will likely receive these changes later this month.

**Comment by cmschwanke** [comment]
Thank you! I think that's a nice improvement.  I appreciate the ability to
give feedback.

Corbin
