### ISSUE TITLE
Type of site gained for Pangolin?

### ISSUE THREAD

**Issue by gm-bee** [broadinstitute/SpliceAI-lookup#56]
Hi,
I'm wondering if the Pangolin data has information about what type of splice is gained (acceptor v. donor)? 
For example, 7-44192900-C-T shows a gained donor site in the SpliceAI output, but looking at just the Pangolin results would not tell us this. 
Thanks!

**Comment by bw2** [comment]
No, unfortunately the Pangolin model only outputs a probability that a given position is a splice site (eg. P(spliced)) and doesn't distinguish acceptors vs donors:

<img width="336" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/a982d59e-a6a2-45f1-91c6-26d22f5bdf68">

(from https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02664-4)

while the SpliceAI model does output 2 separate probabilities -  P(Acceptor) and P(Donor):
<img width="225" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/47091119-4195-4db8-8009-82e7ff1b6766">

(from https://www.cell.com/cell/fulltext/S0092-8674(18)31629-5 )
