### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by lindenb** [broadinstitute/SpliceAI-lookup#61]
Hi all,

the spliceAI website looks broken today. The Firefox console shows the following message

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://spliceailookup-api.broadinstitute.org/spliceai/?hg=38&distance=500&mask=0&variant=8-140300616-T-G&raw=chr8-140300616-T-G. (Reason: CORS request did not succeed). Status code: (null).

**Comment by bw2** [comment]
Apologies - yes. The server went down 3 hours ago, but is now back online.

**Comment by bw2** [comment]
I will see if I can add better monitoring & redundancy to reduce the chances of a long outage.

**Comment by lindenb** [comment]
thanks !
