### ISSUE TITLE
Request: Most recent pre-computed SpliceAI scores

### ISSUE THREAD

**Issue by wwgordon** [broadinstitute/SpliceAI-lookup#62]
Hello,

I am working on developing a Slivar pipeline to run parallel to our lab's Seqr pipeline, and one remaining area of discrepancy is our SpliceAI annotations. Would it be possible to obtain the most recent (gencode v44 basic) masked spliceAI pre-computed annotations that SpliceAI-lookup uses?

Thank you for your time and effort,
William Gordon (Chong Lab @ UW-CRDR)

**Comment by bw2** [comment]
Hi William, 

SpliceAI-lookup doesn't use precomputed scores. The model is called directly for each new variant. 
There are newly precomputed SpliceAI and Pangolin delta scores for gnomAD variants that are available publicly within the  gnomAD v4 hail table:
```
ipython3
In [1]: import hail as hl
In [2]: ht = hl.read_table("gs://gcp-public-data--gnomad/release/4.0/ht/exomes/gnomad.exomes.v4.0.sites.ht")
In [3]: ht = ht.filter(hl.is_defined(ht.in_silico_predictors.spliceai_ds_max), keep=True)
In [4]: ht.in_silico_predictors.spliceai_ds_max.take(5)
In [5]: ht.in_silico_predictors.pangolin_largest_ds.take(5)
```
They are based on gencode v39, max distance = 500 and mask=True.
SpliceAI-lookup doesn't use them though. 

-Ben

**Comment by wwgordon** [comment]
Hi Ben,

Thanks for clearing that up for me and pointing me towards the gnomAD v4 hail table!

Cheers,
William
