### ISSUE TITLE
Pangolin Installation

### ISSUE THREAD

**Issue by neilmolyneaux** [broadinstitute/SpliceAI-lookup#63]
I am running into an issue with installation of the version of Pangolin used for SpliceAI-lookup.

I followed the instructions found in the README file here: https://github.com/bw2/Pangolin, with one exception.
I replaced '**git clone https://github.com/tkzeng/Pangolin.git**' with '**git clone https://github.com/bw2/Pangolin.git**'

The former version (from tkzeng), I can install and run without issues.
The latter version (from bw2) gives me the following error when I attempt to run it:

![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/158371245/94e8ff5c-c58f-461c-ab34-f3fbb7f58c69)

Is there another step that needs to be changed to install version 1.0.5 of Pangolin?

**Comment by bw2** [comment]
This should be fixed now. Please update your local copy of bw2/Pangolin and try again.

**Comment by neilmolyneaux** [comment]
It works now. Thank you for the quick fix.
