### ISSUE TITLE
API call failed

### ISSUE THREAD

**Issue by mikespiller1** [broadinstitute/SpliceAI-lookup#64]
Hello, I've been getting this error on and off recently. Today it's been down the whole day:

SpliceAI API error: SpliceAI API call failed: Unable to reach server

Pangolin API error: Pangolin API call failed: Unable to reach server

**Comment by bw2** [comment]
Hi, our automatic monitoring did not report any downtime today. Also, I just tested it and it works for me. 

In general, I'm aware of brief windows when the server may be getting overloaded during peak usage hours (~4am to 6am EST). We're working on scaling the backend to address this.
