### ISSUE TITLE
Unable to reach server

### ISSUE THREAD

**Issue by martbro** [broadinstitute/SpliceAI-lookup#65]
Hi,
When trying to look up variants at https://spliceailookup.broadinstitute.org/#variant=chr8-140300616-T-G&hg=38&distance=500&mask=0&ra=0, I get the following error:
"SpliceAI API error: SpliceAI API call failed: Unable to reach server
Pangolin API error: Pangolin API call failed: Unable to reach server"

Is there anything wrong with the server?
Thank you very much in advance and thanks a lot for SpliceAI and Pangolin :)
Martin

**Comment by bw2** [comment]
Hi Martin, 

It's working for me. Are you able to access it now? If not, are you able to access other websites such as https://gtexportal.org/home/ ?

**Comment by martbro** [comment]
Oh I see, I tried using an internet connection that was not my work internet connection and it works fine so I guess the problem has to do with internet security management on my organisation's side

**Comment by bw2** [comment]
One or two other people have reported similar issues. Glad you have an option that works.
