### ISSUE TITLE
Missing certificate chain 

### ISSUE THREAD

**Issue by Pacdam** [broadinstitute/SpliceAI-lookup#66]
Hello,

We have increased security in our organization and we have a problem with the certificate of spliceailookup-api.broadinstitute.org.
The certificate is present but the chain is missing.

Result from sslshopper.com:
![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/9060611/570d53f7-8539-40f6-add1-8bdcc5a6b06b)

Thank you for your help.

P.S. In comparaison, this is a good example of spliceailookup.broadinstitute.org:
![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/9060611/45e62916-c33b-470a-8c99-828ba03047d8)

**Comment by bw2** [comment]
Thanks for the detailed troubleshooting of this. 
I'm working on switching to a new backend that will hopefully resolve this. 
If you'd like to test it out, I've already ported https://liftover.broadinstitute.org/ to the new host, so you can try accessing
https://liftover.broadinstitute.org/#input=chr8%3A141310715%20T%3EG&hg=hg19-to-hg38

If it works, you should see
<img width="1051" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/317bedcb-6cc6-4168-bbfa-a340e1e012eb">

**Comment by Pacdam** [comment]
This one works great for me !

**Comment by bw2** [comment]
The API is now running on Google Cloud Run so this should no longer be an issue.
