### ISSUE TITLE
Flank distance maximum changed?

### ISSUE THREAD

**Issue by NM-G08** [broadinstitute/SpliceAI-lookup#68]
Hello,

Did the maximum flank distance change in SpliceAI?  It used to be 10000 (which I assumed was equivalent to the 5000 nt on both sides of the variant), but I'm now getting an error when I put 10000 in.

Do we now have to put in 5000 and that will be the same as 10000 before?  If so, I didn't notice an update on the left side of the screen, and hovering over the question mark still lists 10000 as the maximum value in spite of the error that comes up.

Thanks for looking at this!

---
![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/43679337/fbe18108-b608-4099-84ad-2846627eb545)

**Comment by bw2** [comment]
Apologies, the limit is now back to 10,000. 
I would be interested to see any examples of variants where using a distance of 10,000 results in a different score from 5,000.
