### ISSUE TITLE
SpliceAI-lookup & RefSeq

### ISSUE THREAD

**Issue by amartins1** [broadinstitute/SpliceAI-lookup#7]
Hi,
Many thanks for having developed the SpliceAI-lookup interface (https://spliceailookup.broadinstitute.org/)!
I just tried to use it for the first time, notably to analyze
NM_1287174.1(ABCC8):c.2924-9G>A
(Saint-Martin et al Hum Mutat 2021; Supp Table S2).
Unfortunately, I got the following error message
"Ensembl API error: Unable to parse HGVS notation 'NM_1287174.1(ABCC8):c.2924-9G>A': Could not get a Transcript object for 'NM_1287174.1".
Is there a problem with the RefSeq NM_1287174.1?
Can you please advise?
I thank you in advance for your help.
Regards,
Alexandra

**Comment by bw2** [comment]
I'm not finding NM_12387174.1 in RefSeq (https://www.ncbi.nlm.nih.gov/nuccore/?term=NM_1287174.1+AND+srcdb_refseq%5BPROP%5D ) or other online resources like GeneCards. 
Could you double-check this transcript ID and/or try a different isoform (assuming there's one that wouldn't change the c. coordinates)?

**Comment by amartins1** [comment]
Hi,
Thanks for your prompt reply
it's NM_1287174.1 (not NM_12387174.1)
https://www-ncbi-nlm-nih-gov.proxy.insermbiblio.inist.fr/search/all/?term=NM_1287174.1

i.e. ABCC8 transcript variant 1

**Comment by bw2** [comment]
When I search RefSeq for NM_1287174.1  I don't get any results (please my previous link - it has the ID without the typo). I can't access the link you shared - it takes me to a page that looks like 
![image](https://user-images.githubusercontent.com/6240170/120532793-0fb24800-c3ae-11eb-8492-6c2fceeb92b8.png)

**Comment by amartins1** [comment]
Can you please try this other link
https://www.ncbi.nlm.nih.gov/search/all/?term=NM_1287174.1
Hope it will work this time

**Comment by bw2** [comment]
Interesting.. yes that works.
That NCBI page shows the id as NM_001287174.1
The if I change
NM_1287174.1(ABCC8):c.2924-9G>A
to
NM_001287174.1(ABCC8):c.2924-9G>A
it also works in SpliceAI-lookup:
https://spliceailookup.broadinstitute.org/#variant=NM_001287174.1(ABCC8)%3Ac.2924-9G%3EA&hg=38&distance=50&mask=0&precomputed=1

**Comment by amartins1** [comment]
Ooops...
Many thanks for finding the source of the problem!
I've just tried the correct NM_  with D=500 and it worked fine with Hg38, but not with Hg19.
Error message = Ensembl API error: Unable to parse HGVS notation 'NM_001287174.1(ABCC8):c.2924-9G>A': Could not get a Transcript object for 'NM_001287174.1'

**Comment by bw2** [comment]
It seems the transcript isn't defined for hg19 for some reason. Is there a reason you want to get the scores using hg19 rather than hg38?

**Comment by amartins1** [comment]
An old habit...
Will switch to Hg38 to analyse 'NM_001287174.1(ABCC8) with SpliceAI-Lookup.
Thanks for your help!
