### ISSUE TITLE
What is the plotting convention for the location of the delta bar in the viewer?

### ISSUE THREAD

**Issue by SophieCandille** [broadinstitute/SpliceAI-lookup#70]
Hello,
Because in the viewer the bars that indicate the delta scores are on top of a base and not in between bases, I found myself wondering if that means SpliceAI predicts the splicing score change happens to the left or to the right of the bar. I played around with different genes and on different strands, inventing basic single nucleotide changes at +/-1,2 where I know where the delta should be and came to the conclusion that it depends on which side of the exon we are looking in the following way:
Somehow the bar is always set on the last or first bp of the exon so the predicting splice change is either on the left or the right side of the bar(see the vertical arrows on my drawing). 

I was wondering if that was the intent and also if so if you could share the overarching principle by which this is decided.(just so I can understand it better and be more confident of in between what base the change is predicted to happen). 
I would have guessed that it would have been easier to do something like for example "the bar is always placed on the base to the left of the splice change on the genome + strand" which would mean for eg on my drawing, top situation, the bar would be moved over to be on the first base of the intron on the donor side and would be unchanged on the acceptor side.
It would be ideal to place the bars between the bases, then it would be completely unambiguous.
Where the change is predicted is actually  super important to figure out if some event is predicted to change the frame or not. 
Thanks so much for your help with this question.

<img width="854" alt="Screenshot 2024-03-08 at 8 30 45 AM" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/131707661/4037e23f-8f69-428f-9b21-280a242ccc11">

**Comment by SophieCandille** [comment]
Hello, just following up on this question. Would it be possible to get some help on this topic?
Thank you so much

**Comment by bw2** [comment]
Hi @SophieCandille, apologies for the delay on this. I'm still not sure about the answer and need to trace it back through the code stack.

**Comment by bw2** [comment]
Hi @SophieCandille , through discussions with colleagues (particularly Heather Zimmermann), I learned that SpliceAI assigns the "0" position to the first nucleotide of the exon for acceptors and the last nucleotide of the exon for donors, so the splice site precedes the indicated position for AGs and ALs and follows the indicated position for DGs and DLs.
I've now adjusted the visualizations accordingly, so that SpliceAI scores are shown between bases, as you proposed. 

Interestingly, I don't think it's possible to fix this for Pangolin predictions since it appears to be computing the "0" position the same way as SpliceAI, but then provides no way to distinguish donors from acceptors.

**Comment by SophieCandille** [comment]
Hello, 
and thank you for improving the browser. It is really much easier to read imo. 
 I just noticed there is likely a bug for example: NM_000179.3:c.3439-1G>T
Looks like the plotting of the delta bars is off by 1 bp: the red bar for example should be between the 2 Gs but it is between the G and C.
![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/131707661/080a8728-5de5-4142-ae3c-2a2fd8560f5f)
Would be good to check that for genes on either strand, the plotting happens as expected for canonical splice site variants. It could be the opposite problem for a gene on the minus strand I am guessing. 
Thanks again for being willing to improve the browser.

**Comment by bw2** [comment]
Thanks for reporting this! I thought I had checked the different orientations, but see that I missed that one. 
It should be fixed now if you hard-refresh the page (command-shift-R on Mac or ctrl-shift-R on windows) - for example 
https://spliceailookup.broadinstitute.org/#variant=6-31740453-G-T&hg=38&distance=500&mask=0&ra=0

<img width="493" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/7f236f9a-e0a1-4bfe-a83b-8ee7893aa4a7">

**Comment by SophieCandille** [comment]
Thank you very much for your diligence.
