### ISSUE TITLE
Issue with API Timeout Error

### ISSUE THREAD

**Issue by kaycho88** [broadinstitute/SpliceAI-lookup#71]
Hi there,
I wanted to report an ongoing issue with the API endpoint at https://spliceailookup-api.broadinstitute.org/spliceai?hg=37&mask=0&distance=1000&variant=chr14-21863282-T-C&precomputed=0. It appears that requests to this API are consistently timing out, making it impossible to access the data.

Furthermore, the example request provided in the GitHub README is also failing to execute. I've double-checked by performing the same request directly on the SpliceAI-lookup website (https://spliceailookup.broadinstitute.org/), and it works without any issues. This leads me to believe that the problem may lie specifically with the API itself.

Could you please confirm if there have been any recent updates or modifications to the API request URL address? Alternatively, is there a possibility that the API server is currently experiencing downtime?

Your assistance in resolving this matter would be greatly appreciated.

**Comment by bw2** [comment]
Hi @kaycho88 , the server has moved to a different set of urls. I just updated the README with more info.
