### ISSUE TITLE
Ensembl API is unable to parse the variant

### ISSUE THREAD

**Issue by cfcranston** [broadinstitute/SpliceAI-lookup#73]
Hi there, I've been getting the following error for the past few weeks: 'Ensembl API is unable to parse the variant'. I get this error for any variant that I try, and I've tried entering variants in different formats and tried using different computers as well, but I get the same error. Meanwhile, other people using the same computers have no problems using SpliceAI. Any help would be much appreciated :))

![image](https://github.com/broadinstitute/SpliceAI-lookup/assets/169659353/48be3b63-5f0b-4fef-920b-970c9ebde8b0)

**Comment by bw2** [comment]
Hi. Do you get the same error if you enter the variants in chrom-pos-ref-alt format (eg. chr8-140300616-T-G)? 

This could be an IT security/firewall issue. 
Are these different computers connected to different networks?  
Which browsers and operating systems have you tried?

To troubleshoot, could you open Chrome and do 
1) open the SpliceAI-lookup page
2) show Developer tools <img width="616" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/ec85302d-9e82-4b69-bfa7-a44d09403968">
3) click on the Network tab
4) enter one of the example variants (eg. `NM_001089.3(ABCA3):c.875A>T (p.Glu292Val)`  )
5) click submit and share the screenshot

It should look like
<img width="1792" alt="image" src="https://github.com/broadinstitute/SpliceAI-lookup/assets/6240170/12e5e5f2-fd3f-440c-b4e1-8ceb223c182f">
