### ISSUE TITLE
Clarify which version of tensorflow is used

### ISSUE THREAD

**Issue by bpow** [broadinstitute/SpliceAI-lookup#75]
`requirements.txt` in the source root pins tensorflow to `tensorflow==1.14.0` (with comment about python3.6 on centos7).

But `google_cloud_run_services/docker/spliceai/Dockerfile` just runs `python3 -m pip install tensorflow`, so it probably gets the most recent version of tensorflow available (currently 2.16.1).

Is there any need to pin to an earlier version of tensorflow at this point, or was that an artifact of how/where the server was running before the gcp setup was made?

**Comment by bw2** [comment]
Yes, there no longer a need to use the old version. The latest version (2.16.1) appears to be working fine, so I've updated the line you pointed out to == 2.16.1
