### ISSUE TITLE
ModuleNotFoundError: No module named 'bw2_annotation_utils'

### ISSUE THREAD

**Issue by xiucz** [broadinstitute/SpliceAI-lookup#78]
Hi, 

The 'bw2_annotation_utils' module seems to be missing from the 'requirements.txt' file. Could you please verify it? (https://github.com/broadinstitute/SpliceAI-lookup/blob/master/annotations/update_SpliceAI_annotation_txt_files.sh)

`pip install bw2-annotation-utils -i https://pypi.org/simple` cannot work also.

Best,
xiucz

**Comment by bw2** [comment]
Hi @xiucz , please try 

```python3 -m pip install git+https://github.com/bw2/annotation-utils```

**Comment by xiucz** [comment]
It works now.
