### ISSUE TITLE
TGG Viewer: Authorization is required, but Google oAuth has not been initalized. Contact your site administrator for assistance.: undefined

### ISSUE THREAD

**Issue by CaptainLabMan** [broadinstitute/SpliceAI-lookup#79]
TGG Viewer: Authorization is required, but Google oAuth has not been initalized. Contact your site administrator for assistance.: undefined
It's not a SpliceAI issue, but i didn't find any topics for TGG Viewer issues.
![Снимок экрана 2024-08-27 в 18 24 26](https://github.com/user-attachments/assets/dcfdb2ad-e486-4d5d-98a6-aa13d41c9c76)
I think that is wrong behavior

**Comment by bw2** [comment]
I'm not sure which Google Storage file paths are triggering that error. 
Let's see if we can troubleshoot. 

What url does TGG-viewer show in the "Initial settings" box?
If it's not https://tgg-viewer.broadinstitute.org/default_config.json , can you set it to that and hit "Apply"?

Also, if you open https://tgg-viewer.broadinstitute.org/default_config.json directly in your browser, it lists all the metadata and file paths that TGG viewer uses to populate the left side-bar. If you're getting that error when trying to load one of the IGV tracks listed in the sidebar, you can find the underlying data path in the JSON file and see if/why you get an error when accessing the data file directly outside TGG-viewer.

Another thing to check is, when you're logged with that gmail account, are you able to go to your Google Storage Console @ 
https://console.cloud.google.com/storage/browser  and see any files there?
