### ISSUE TITLE
DECIPHER link broken, links to old domain

### ISSUE THREAD

**Issue by stobo91** [broadinstitute/SpliceAI-lookup#80]
REQUIRED: If the issue is about a specific variant or results page (or you have an example), please copy-paste the variant here and/or provide a link to the results page where you see the issue. 

---
OPTIONAL: If you'd like to also share a screenshot:

MacOS:   Press Command+Shift+4, select a region of the page, then paste the image here.
Windows:  Press Windows Logo Key + PrtScn   or   Fn + Windows logo key + Space Bar. Then, in File Explorer, open the Pictures > Screenshots folder and drag the image here.
![SpliceAI](https://github.com/user-attachments/assets/058a97de-c4f4-43d4-b313-8d29a3b5e442)
![DECIPHER](https://github.com/user-attachments/assets/dc5a91b4-a079-4f61-81a7-454ebe598d27)

Decipher link for variant on SpliceAI should link to https://www.deciphergenomics.org/ domain not https://decipher.sanger.ac.uk/

**Comment by bw2** [comment]
Thanks for reporting this
