### ISSUE TITLE
Precalculated SpliceAI score for GRCh38 

### ISSUE THREAD

**Issue by xiaoxi98** [broadinstitute/SpliceAI-lookup#83]
Are there any precalculated SpliceAI scores for WGE/WES using GRCh38 that can be downloaded? Thanks.

**Comment by bw2** [comment]
Hi @xiaoxi98 , SpliceAI-lookup doesn't provide or use precomputed tables, but gnomAD does provide precomputed SpliceAI and Pangolin scores for gnomAD variants.  See 

https://gnomad.broadinstitute.org/help/v4-hts#in-silico-predictors
and 
https://gnomad.broadinstitute.org/downloads#v4
