### ISSUE TITLE
SpliceAI scores not showing in IGV, possibly due to a gene on the opposite strand?

### ISSUE THREAD

**Issue by SamBryen** [broadinstitute/SpliceAI-lookup#85]
The SpliceAI scores for the variant [chr10-71755358-C-G](https://spliceailookup.broadinstitute.org/#variant=chr10-71755358-C-G&hg=38&bc=basic&distance=500&mask=0&ra=1) (hg38) are displayed in the table for the gene VSIR but do not show up in the IGV window. Pangolin is displaying scores normally.

My guess is that the IGV window is prioritising genes in the forward direction when deciding which transcript to display, in this case CDH23, but I'm not sure. Thanks!

![image](https://github.com/user-attachments/assets/a0c354e7-2d8f-47d3-8a31-8e0696a3f2e3)

**Comment by bw2** [comment]
Thanks for reporting the issue. The explanation is close to what you wrote. 
Given multiple transcripts, it currently choose the one to display in IGV based on their relative "priority" as follows:
```
TRANSCRIPT_PRIORITY_ORDER = {
    "MS": 3,  # MANE select transcript
    "MP": 2,  # MANE plus clinical transcript
    "C": 1,   # canonical transcript
    "N": 0
}
```
If two transcripts have the same priority, as in your case where both are MANE select transcripts, it just displays the first one. 
I can update it so that it breaks the tie by selecting the one with the highest sum of delta scores. 
What do you think?

**Comment by bw2** [comment]
For Pangolin, it already displays the gene with the highest total scores, regardless of transcript priority.

**Comment by SamBryen** [comment]
Thanks Ben, I think that is a good solution that would work for almost all cases. 

The best solution would probably be to be able to select which transcript you would like IGV to display scores for, either by having a selectable list of transcripts or by taking this from the variant nomenclature entered when available (eg. NM_022153.2:c.676+1G>C). I imagine both of these options would require a lot more work than your solution, and would only be better is a very small number of cases. So breaking ties with the highest sum of delta scores makes sense to me, thanks!

**Comment by bw2** [comment]
Great. I agree, allowing users to selecting transcripts would be be a more powerful approach. 
Perhaps we can revisit if / when there's a clear need for it. 
The one downside is it might significantly increase the API response size for genes with many transcripts.

**Comment by bw2** [comment]
Let me know if you run into this issue again!

**Comment by SamBryen** [comment]
Awesome, thanks Ben will do! I'll let you know if my theoretical use case ever comes up that would require the other solution, but it might be incredibly unlikely for all I know. Thanks again!
