### ISSUE TITLE
Genes with introns longer than 10 000 nt

### ISSUE THREAD

**Issue by amartins1** [broadinstitute/SpliceAI-lookup#86]
Hi
I wonder if one can extend the SpliceAI "max distance" window above 10 000 nt (the current maximum allowed value), notably to analyze variants mapping near introns larger than 10 000 nucleotides?
Example; the DMD gene has several exons with a size >10 kb
How to proceed in a case like this?
Regards
Alexandra

REQUIRED: If the issue is about a specific variant or results page (or you have an example), please copy-paste the variant here and/or provide a link to the results page where you see the issue. 

---
OPTIONAL: If you'd like to also share a screenshot:

MacOS:   Press Command+Shift+4, select a region of the page, then paste the image here.
Windows:  Press Windows Logo Key + PrtScn   or   Fn + Windows logo key + Space Bar. Then, in File Explorer, open the Pictures > Screenshots folder and drag the image here.

**Comment by bw2** [comment]
Hi @amartins1 , I don't think it's possible to extend SpliceAI this way without rebuilding it from the beginning. 
The 10k limit is a core property of the current SpliceAI algorithm. 
If your variant is near the annotated splice donor or splice acceptor (eg. within the extend region of the splicing motif), you could try SpliceVault - which, the way I understand it - is an orthogonal way of predicting what kinds of exon skipping events are most likely to occur when a variant disrupts a known splice site. These exon skipping predictions are not limited to a particular window size since they are just based on observed mis-splicing events that occur naturally at low levels. 

--


<br class="Apple-interchange-newline">

**Comment by bw2** [comment]
Another resource to check is 
https://compbio.ccia.org.au/splicevardb/
described here 
https://www.cell.com/ajhg/fulltext/S0002-9297(24)00288-X

**Comment by bw2** [comment]
and I more very relevant paper that just came out:
https://www.nature.com/articles/s42003-024-07298-9
They trained a new model with a 45kb window (and a different neural-net architecture) and the compared results to SpliceAI with a 10kb window - and found basically no difference in accuracy:
".. we see that the models agree on 175,825 splice sites and 664,757,322 non-splice sites, and they disagree on 3599 splice sites and 3254 non-splice sites. For cases where the the predictions disagree, Transformer-45k has 0.609 accuracy (4172 correct sites) and SpliceAI-10k has 0.391 accuracy (2681 correct sites)."

**Comment by amartins1** [comment]
Hi Ben,
Many thanks for all your tips!!
All best,
Alexandra

Le Lundi, Décembre 09, 2024 13:32 CET, Ben Weisburd ***@***.***> a écrit:
 
 
and 1 more very relevant paper that just came out:
https://www.nature.com/articles/s42003-024-07298-9
They trained a new model with a 45kb window (and a different neural-net architecture) and the compared results to SpliceAI with a 10kb window - and found basically no difference in accuracy:
".. we see that the models agree on 175,825 splice sites and 664,757,322 non-splice sites, and they disagree on 3599 splice sites and 3254 non-splice sites. For cases where the the predictions disagree, Transformer-45k has 0.609 accuracy (4172 correct sites) and SpliceAI-10k has 0.391 accuracy (2681 correct sites)."
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
--
Alexandra Martins, PhD, HDR
Inserm researcher (CRHC)
Group Leader
INSERM U1245, Cancer and Brain Genomics (CBG)
UFR Santé, Univ Rouen Normandie
22 Boulevard Gambetta
76183 Rouen
France
phone# (office): + 33 0(2) 35 14 83 14
email: ***@***.***
ORCID: 0000-0003-4322-8497

**Comment by amartins1** [comment]
Dear Ben,
Could you please give me some hints on how to interpret the distance values relative to indel variants (deletions and/or insertions) in genes in reverse orientation such as BRCA1?
Distance (of 5'ss/3'ss Loss/Gain) relative to the which nucleotide(s) exactly?
Thanks.
All best,
Alexandra
 
 

Le Lundi, Décembre 09, 2024 15:01 CET, "Alexandra Martins" ***@***.***> a écrit:

 
Hi Ben,
Many thanks for all your tips!!
All best,
Alexandra

Le Lundi, Décembre 09, 2024 13:32 CET, Ben Weisburd ***@***.***> a écrit:
 
 
and 1 more very relevant paper that just came out:
https://www.nature.com/articles/s42003-024-07298-9
They trained a new model with a 45kb window (and a different neural-net architecture) and the compared results to SpliceAI with a 10kb window - and found basically no difference in accuracy:
".. we see that the models agree on 175,825 splice sites and 664,757,322 non-splice sites, and they disagree on 3599 splice sites and 3254 non-splice sites. For cases where the the predictions disagree, Transformer-45k has 0.609 accuracy (4172 correct sites) and SpliceAI-10k has 0.391 accuracy (2681 correct sites)."
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/broadinstitute/SpliceAI-lookup/issues/86#issuecomment-2527801462",
"url": "https://github.com/broadinstitute/SpliceAI-lookup/issues/86#issuecomment-2527801462",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

--
Alexandra Martins, PhD, HDR
Inserm researcher (CRHC)
Group Leader
INSERM U1245, Cancer and Brain Genomics (CBG)
UFR Santé, Univ Rouen Normandie
22 Boulevard Gambetta
76183 Rouen
France
phone# (office): + 33 0(2) 35 14 83 14
email: ***@***.***
ORCID: 0000-0003-4322-8497
 

-- 
 
Alexandra Martins, PhD, HDR
Inserm Researcher (CRHC)
Group Leader
Inserm UMR 1245 - Cancer and Brain Genomics
UFR Santé
22 Bvd Gambetta
CS 76183
76183 Rouen Cedex 1
France
phone#: + 33 (0)2 35 14 83 14
email: ***@***.***
https://www.researchgate.net/profile/Alexandra_Martins5
ORCID ID: 0000-0003-4322-8497
 
You may receive this message early in the morning, late, or on weekends.
It does not require, in any way, a response from you outside of working hours.

**Comment by bw2** [comment]
Hi Alexandra, 

The position offsets are relative to the variant's genomic position, and their sign isn't affected by the transcript strand. 

For example, this ClinVar variant: NM_007294.4(BRCA1):c.5331_5332+1delinsCAACAT
can be written as [17:43051061 ACCT > AATGTTG](https://spliceailookup.broadinstitute.org/#variant=NM_007294.4(BRCA1)%3Ac.5331_5332%2B1delinsCAACAT&hg=38&bc=basic&distance=500&mask=0&ra=0)
and has Acceptor Loss at position 56:

<img width="1598" height="237" alt="Image" src="https://github.com/user-attachments/assets/c7ab5380-da85-45aa-ba6b-cce03386e362" />

The easiest way to interpret the position offset is to look at the visualization displayed when you click "Show" at the bottom:

<img width="1689" height="711" alt="Image" src="https://github.com/user-attachments/assets/bbec4f99-3558-44a4-b8cc-fd35db252023" />

The 56bp offset is toward the gene's 5' end in this case, and lines up with the annotated acceptor position.
