### ISSUE TITLE
Issue with SpliceAI Website

### ISSUE THREAD

**Issue by emmamiz** [broadinstitute/SpliceAI-lookup#87]
For the past week, the SpliceAI website has not been generating results when I input a variant. I have attempted to use the tool with several different variants across multiple browsers (e.g., Chrome, Firefox, Safari), but the issue persists. Some of my colleagues have also tried accessing the site from different computers and networks, and they are encountering the same problem. Is this a known issue? Are there specific troubleshooting steps I can follow to resolve this?

Any guidance or updates would be greatly appreciated. Thank you for your help!

**Comment by bw2** [comment]
Hi @emmamiz , no there's no known issue currently. Can you provide a screenshot or description of what happens?

**Comment by emmamiz** [comment]
Hi Ben,

Thanks for your quick response. Screenshot below. The website looks normal, but this screenshot was taken after I pressed “submit.”  As you can see, the bottom half of the screenshot is empty. Nothing loads.

***@***.***

From: Ben Weisburd ***@***.***>
Date: Monday, December 9, 2024 at 11:15 AM
To: broadinstitute/SpliceAI-lookup ***@***.***>
Cc: Mizrahi-Powell, Emma ***@***.***>, Mention ***@***.***>
Subject: Re: [broadinstitute/SpliceAI-lookup] Issue with SpliceAI Website (Issue #87)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

[EXTERNAL]

Hi @emmamiz<https://urldefense.com/v3/__https:/github.com/emmamiz__;!!MXfaZl3l!fM_oPLFAp-5ITHFppccd4zmbpegXa1YM3HDUsqpVS-UhaZ82uzkN9u6zNe4g6FGsA2eh_xdk56kfzrccfyzXSX09_AUj-GBnjPLnXg$> , no there's no known issue currently. Can you provide a screenshot or description of what happens?

**Comment by bw2** [comment]
Hmm.. the screenshot didn't go through, but if nothing loads, some error is occuring on the page that I can't reproduce here. 
Can you please open the Developer Console in your browser by doing:

<img width="658" alt="image" src="https://github.com/user-attachments/assets/c22230e7-c3db-4870-9492-361710e1261f">

and share any error messages you see there?

In chrome, normal Console output looks like:
<img width="1787" alt="image" src="https://github.com/user-attachments/assets/8198494e-b5ae-4c40-bd07-71e8d6b90512">

**Comment by bw2** [comment]
This is after I click Submit.

**Comment by emmamiz** [comment]
I see this issue with every variant I tried, and I tried upwards of 20 (including the example variants listed on the webpage).  Example variant here: NM_007294.4:c.4096+1G>A  .   Screenshot of the page and console output attached. 
<img width="1726" alt="Screenshot 2024-12-09 at 1 56 54 PM" src="https://github.com/user-attachments/assets/b6802159-253c-4539-a8f2-363b5378812e">

**Comment by bw2** [comment]
Thanks .. for some reason your browser isn't able to load a library  (TabixIndexedFile) that the latest version of SpliceAI-lookup relies on. I just switched it to a different url. Can you please try hard-reloading the SpliceAI-lookup page 
via Command-Shift-R (or Ctrl-Shift-R on windows) and see if it works now? 

If not, can you tell me what you see when you go to https://unpkg.com/@gmod/tabix/dist/tabix-bundle.js ?

**Comment by emmamiz** [comment]
Fantastic, it works now. Thank you so much!

From: Ben Weisburd ***@***.***>
Date: Monday, December 9, 2024 at 2:18 PM
To: broadinstitute/SpliceAI-lookup ***@***.***>
Cc: Mizrahi-Powell, Emma ***@***.***>, Mention ***@***.***>
Subject: Re: [broadinstitute/SpliceAI-lookup] Issue with SpliceAI Website (Issue #87)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

[EXTERNAL]

Thanks .. for some reason your browser isn't able to load a library (TabixIndexedFile) that the latest version of SpliceAI-lookup relies on. I just switched it to a different url. Can you please try hard-reloading the SpliceAI-lookup page
via Command-Shift-R (or Ctrl-Shift-R on windows) and see if it works now?

If not, can you tell me what you see when you go to ***@***.******@***.***/tabix/dist/tabix-bundle.js__;!!MXfaZl3l!c8KH6CIW9Loy9RvWlNP7vNF9FZpFaIOdAU8V2irOqqW0nuxU65oTWxQ-iSEL25uQBd0bGl3a09pKzB8WN4XKmi0vg1W0wb-o_xaI8Q$> ?

**Comment by bw2** [comment]
Great! Thanks for reporting the issue
